version: '3.8'
services:
  ### MySQL database for Orders
  db-usuario:
    container_name: db-usuario
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ms_usuarios
      MYSQL_USER: rootmysql
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - 3306:3306
    expose:
      - 3306
  
  ### Posgres database for Inventory
  db-agenda:
    container_name: db-agenda
    image: postgres:12.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_agendas
      POSTGRES_USER: rootpostgress
      POSTGRES_PASSWORD: root123
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431
